workflows:
  seawa-app:
    name: Seawa Android Build
    max_build_duration: 10
    environment:
      vars:
        GRADLE_BUILD_FILE: app/build.gradle
    scripts:
      - ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
